version: '3.4'


####### Networks #######

networks:
  networkPortal:

####### Services #######

services:
#-----------------------------------------------------------------------
  dbPortal:
    container_name: dbPortal
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=Aa@123456
      - ACCEPT_EULA=Y
    ports:
      - 8002:1433
    networks:
     - networkPortal
#-----------------------------------------------------------------------
  shj.basearchitecture.web.api:
    container_name: "shjbasearchitecturewebapi"
    image: ${DOCKER_REGISTRY-}shjbasearchitecturewebapi
    build:
      context: .
      dockerfile: src/Prsentation/SHJ.BaseArchitecture.Web.API/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:80"
    depends_on:
      - dbPortal
    ports:
      - 8001:80
    networks:
     - networkPortal
#-----------------------------------------------------------------------