version: '3.4'

####### Networks #######

networks:
  networkPortal:

####### Services #######

services:
#-----------------------------------------------------------------------
  MsSqLServer2019:
    container_name: MsSqLServer2019
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=Aa@123456
      - ACCEPT_EULA=Y
    ports:
      - 8002:1433
    networks:
     - networkPortal
#-----------------------------------------------------------------------
  shj.basearchitecture.web.api:
    container_name: "base_application"
    image: ${DOCKER_REGISTRY-}base_application
    build:
      context: .
      dockerfile: src/Prsentation/SHJ.BaseArchitecture.Web.API/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:80"
    depends_on:
      - MsSqLServer2019
    ports:
      - 8001:80
    networks:
     - networkPortal
#-----------------------------------------------------------------------