version: '3.4'

services:

  dbPortal:
    container_name: dbPortalContainer
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA =Y
      - SA_PASSWORD =Aa@123456
      

  shj.basearchitecture.web.api:
    container_name: "basearchitecture"
    image: ${DOCKER_REGISTRY-}shjbasearchitecturewebapi
    build:
      context: .
      dockerfile: src/Prsentation/SHJ.BaseArchitecture.Web.API/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - dbPortal
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "DatabaseName=dbPortal"
      - "DataSource=dbPortal"
      - "DB_Password=Aa@123456"
